---
- name: 'user_group:group:defaults'
  ansible.builtin.include_tasks: './group_defaults.yaml'

# Now we can use 'group' for original input and 'group_instance' for the final object

- name: "user_group:group:configure:{{ group_instance.name }}"
  ansible.builtin.group: "{{ group_instance }}"
  tags:
    - 'skip_ansible_lint'
