---
- name: 'user_group:user:defaults'
  ansible.builtin.include_tasks: './user_defaults.yaml'

# Now we can use 'user' for original input and 'user_instance' for the final object

- name: "user_group:user:remove:{{ user_instance.name }}"
  ansible.builtin.user: "{{ user_instance }}"
  tags:
    - 'skip_ansible_lint'
